# Generated by Django 4.2.7 on 2023-12-03 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('des', models.TextField()),
                ('duration', models.CharField(max_length=20)),
                ('img', models.ImageField(upload_to='photo')),
            ],
        ),
    ]
