# Generated by Django 4.2.7 on 2023-12-06 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0003_department_enquiryform_course1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enquiryform',
            name='course',
        ),
        migrations.RemoveField(
            model_name='enquiryform',
            name='department',
        ),
        migrations.AddField(
            model_name='enquiryform',
            name='course_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='enquiryform',
            name='department_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Course1',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
